### ISSUE TITLE
/telegram/settings internal error

### ISSUE THREAD

**Issue by artur9010** [NodeBB-Community/nodebb-plugin-telegram-notifications#15]
NodeBB 1.10.1
https://ucraft.pl/telegram/settings
```
/api/telegram/settings
pubsub.once is not a function
```

**Comment by exomarty** [comment]
https://community.nodebb.org/post/68615

**Comment by vanch** [comment]
NodeBB v1.10.1, Node 8.11.3@sha256:625d0b446f63b2d051c7b2a468f6cee63536dec716f09afcf9ae1c575d9b953a, Plugin v0.2.1.

I am not JS developer. I am not even developer. Trying to understand the issue.
So pubsub is some pattern in JS to communicate with modules. NodeBB has it's own wrapper in `./src/pubsub.js`. But I can't find this broken function `.once` anywhere :(

Doesn't that mean that this plugin supports only Redis installations? https://github.com/NodeBB-Community/nodebb-plugin-telegram-notifications/pull/1

**Comment by wellenreiter01** [comment]
in library.js replace the 'once' with 'on'

That solved the problem for me

    controllers.getTelegramBotSettings = function (req, res, next) {
    		// Renders template (*Renderiza la plantilla)
    		pubsub.on('telegram:me', function(me){
    //		pubsub.once('telegram:me', function(me){
    			res.render('telegrambot/telegramusersettings', {botname:me.username});
    		});
    		pubsub.publish('telegram:getMe');
    	};
