### ISSUE TITLE
UserID not found.. Put your TelegramID again in the telegram settings of the forum. :(

### ISSUE THREAD

**Issue by craigusus** [NodeBB-Community/nodebb-plugin-telegram-notifications#4]
I have followed the instructions as best I can (even with incorrect wording/translations).

But am getting the error message above when sending a message to my bot.

**Comment by segura2010** [comment]
I replied in other issue. But i think you are trying to configure your userid in admin's page. Obviously, admin's page is designed to configure your bot, not your userid. Userid must be configured in user's settings.

**Comment by craigusus** [comment]
Understood.
Sorry for cross posting. Probably due to lack of coffee !!

**Comment by exomarty** [comment]
just for the record the configuration on the string should be something like this

![screenshot_2](https://cloud.githubusercontent.com/assets/10746278/15448606/1149b04a-1f67-11e6-8174-45f906200ce5.png)
