### ISSUE TITLE
Access to domain/telegram/settings without logging in

### ISSUE THREAD

**Issue by craigusus** [NodeBB-Community/nodebb-plugin-telegram-notifications#6]
Sorry me again...

I have managed to get the bot working from other posts.
My reply from my bot now says...
`Your Telegram ID is: {userid}. Please copy and paste this here: https://mydomain/telegram/settings then click Save.`

But I can access this page without logging in. Is this a nodebb-plugin-telegram-notifications issue or a nodebb issue ?

Thanks.

**Comment by segura2010** [comment]
Yes, it is an issue of nodebb-plugin-telegram-notifications. I think it should check if user have permission to access and configure his id. I think that to fix it they should add "pluginMiddleware.isLoggedIn" here: https://github.com/NodeBB-Community/nodebb-plugin-telegram-notifications/blob/master/library.js#L47

**Comment by craigusus** [comment]
I just tried that line and broke it even more ! :(
I'll wait for an update :p
